config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
  end
  delete :cart_items, to: 'public/cart_items#destroy_all', as: 'cart_items'
  namespace :admin do
    resources :genres, only: [:new, :index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :order_items, only: [:update]

  end


  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
  end
  namespace :public do
    resources :items, only: [:index,:show] do
  collection do
        get 'search'
       end
    end
  end



  root to: 'homes#top'
  get "/homes/about" => "homes#about", as: 'about'

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    patch "/orders/:id/status" => "orders#status_update", as: "status"
    patch "/orders/:id/making_status" => "orders#making_status_update", as: "making_status"
  end


  namespace :public do
    post "/orders/confirm"=>"orders#confirm", as: 'confirm'
    get "/orders/thankyou"=>"orders#thankyou", as: 'thankyou'
    resources :orders, only: [:new, :index, :show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :public do
    resources :customers
  end

  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'public/customers#unsubscribe', as: 'customer_unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'public/customers#withdrawal', as: 'customers_withdrawal'

  namespace :admin do
    resources :customers
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true




  def  address_display
    '〒'  +  postcode  +  ' '  +  address  +  ' '  +  name
  
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    validates :quantity, presence: true
    def subtotal
        item.add_tax_price * quantity
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items, dependent: :destroy

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_item, dependent: :destroy
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    with_options presence: true do
      validates :name, uniqueness: true
      validates :body
      validates :genre_id
      validates :price
    end
    validates :is_active, inclusion:{in: [true, false]}
    has_one_attached :product_image
    
    def get_product_image(width, height)
      unless product_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpeg')
        product_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      product_image.variant(resize_to_limit: [width, height]).processed
    end
    def add_tax_price
        (self.price * 1.10).round
    end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { wait: 0 ,confirm: 1 ,product: 2 ,ready: 3 ,sent: 4 }
 
 def subtotal
  product.with_tax_price * quantity
 end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # 注文ステータス（0=着手不可 / 1=製作待ち / 2=製作中 / 3=製作完了）
  enum status: {impossible:0, wait:1, midst:2, completion:3}

  belongs_to :order
  belongs_to :item
  
  def subtotal
    item.add_tax_price * quantity
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController


def index
    @addresses = Address.all
    @address = Address.new
end

def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path
    else
      render :index
    end
end

def edit
    @address = Address.find(params[:id])
end

def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render :edit
    end
end

def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
end

private
def address_params
    params.require(:address).permit(:postcode, :address, :name)
end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all
    @order_items = OrderItem.all
  end

  def show
    @order = Order.find(params[:id])
    @order.postage = 800
    @order_items = OrderItem.all
    @total = 0
    
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @quantity = Item.count
    @genres = Genre.all
  end

  def about
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h5 class="my-3">注文履歴一覧</h5>
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order.id) %>
              </td>
              <td><%= order.customer.last_name + order.customer.first_name %></td>
              <td>
                <%= @order_items.where(order_id: order.id).sum(:quantity) %>
              </td>
              <td><%= order.status_i18n %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h5 class="my-3">注文履歴詳細</h5>
      <label>購入者</label>
      <%= link_to @order.name, admin_customer_path(@order.customer_id) %><br>

      <label>注文日</label>
      <%= @order.created_at.to_s(:datetime_jp) %><br>

      <label>配送先</label>
      <%= @order.address %><br>

      <label>支払方法</label>
      <%= @order.payment_method_i18n %><br>

      <label>注文ステータス</label>
      <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
        <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
        <%= f.submit '更新', class: 'btn btn-success' %>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item| %>
              <tr>
                <td><%= order_item.item.name %></td>
                <td><%= order_item.item.add_tax_price %>円</td>
                <td><%= order_item.quantity %>個</td>
                <td><%= order_item.item.add_tax_price * order_item.quantity %>円</td>
                <td>
                  <%= form_with model: order_item, url: admin_order_item_path(order_item.id) do |f| %>
                    <%= f.select :status, OrderItem.statuses.keys.map {|k| [I18n.t("enums.order_item.status.#{k}"), k]} %>
                    <%= f.submit '更新', class: 'btn btn-success' %>
                  <% end %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
      <label>商品合計</label><% @total = 0 %>
      <span><% @order.order_items.each do |order_item|%>
            <% @total += order_item.total_payment %>
             <% end %>
             <%= @total %>円</span><br>
      <label>送料</label>
      <span><%= @order.postage %>円</span><br>
      <label>請求額合計</label>
      <span><%= @total += @order.postage %>円</span>
    </div>
  </div>
</div>