config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
  end
  delete :cart_items, to: 'public/cart_items#destroy_all', as: 'cart_items'
  namespace :admin do
    resources :genres, only: [:new, :index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :order_items, only: [:update]

  end


  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
  end
  namespace :public do
    resources :items, only: [:index,:show] do
  collection do
        get 'search'
       end
    end
  end



  root to: 'homes#top'
  get "/homes/about" => "homes#about", as: 'about'

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    patch "/orders/:id/status" => "orders#status_update", as: "status"
    patch "/orders/:id/making_status" => "orders#making_status_update", as: "making_status"
  end


  namespace :public do
    post "/orders/confirm"=>"orders#confirm", as: 'confirm'
    get "/orders/thankyou"=>"orders#thankyou", as: 'thankyou'
    resources :orders, only: [:new, :index, :show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :public do
    resources :customers
  end

  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'public/customers#unsubscribe', as: 'customer_unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'public/customers#withdrawal', as: 'customers_withdrawal'

  namespace :admin do
    resources :customers
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true




  def  address_display
    '〒'  +  postcode  +  ' '  +  address  +  ' '  +  name
  
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    validates :quantity, presence: true
    def subtotal
        item.add_tax_price * quantity
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items, dependent: :destroy

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_item, dependent: :destroy
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    with_options presence: true do
      validates :name, uniqueness: true
      validates :body
      validates :genre_id
      validates :price
    end
    validates :is_active, inclusion:{in: [true, false]}
    has_one_attached :product_image
    
    def get_product_image(width, height)
      unless product_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpeg')
        product_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      product_image.variant(resize_to_limit: [width, height]).processed
    end
    def add_tax_price
        (self.price * 1.10).round
    end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { wait: 0 ,confirm: 1 ,product: 2 ,ready: 3 ,sent: 4 }
 
 def subtotal
  product.with_tax_price * quantity
 end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # 注文ステータス（0=着手不可 / 1=製作待ち / 2=製作中 / 3=製作完了）
  enum status: {impossible:0, wait:1, midst:2, completion:3}

  belongs_to :order
  belongs_to :item
  
  def subtotal
    item.add_tax_price * quantity
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController


def index
    @addresses = Address.all
    @address = Address.new
end

def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path
    else
      render :index
    end
end

def edit
    @address = Address.find(params[:id])
end

def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render :edit
    end
end

def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
end

private
def address_params
    params.require(:address).permit(:postcode, :address, :name)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @quantity = Item.count
    @genres = Genre.all
  end

  def about
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/addresses/edit.html.erb
<div class="container my-5">
<div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        配送先編集
      </h4>
    </div>
  </div>
  <%= form_with model: @address, url: address_path, method: :patch do |f| %>
    <div class="row my-3">
      <table class="table">
        <tbody>
          <th>郵便番号（ハイフンなし）</th>
            <td>
              <%= f.text_field :postcode, class:"form-control" %>
            </td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address, class:"form-control" %></td>
          </tr>
          <tr>
            <th>宛名</th>
            <td><%= f.text_field :name, class:"form-control" %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-2 text-right">
        <%= f.submit '変更を保存', class:"btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/addresses/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        配送先登録/一覧
      </h4>
    </div>
  </div>
  <%= form_with model: @address, url: addresses_path, method: :post do |f| %>
  <div class="row my-2">
    <table class="table">
      <tr>
        <th>郵便番号（ハイフンなし）</th>
        <td><%= f.text_field :postcode, class:"form-control" %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= f.text_field :address, class:"form-control" %></td>
      </tr>
      <tr>
        <th>宛名</th>
        <td><%= f.text_field :name, class:"form-control" %></td>
      </tr>
    </table>
    <div class="col-md-2 text-right">
      <%= f.submit "新規登録", class:"btn btn-danger" %>
    </div>
  </div>
  <% end %>
  <div class="row my-5">
    <table class="table table-bordered">
      <thaed class="bg-light">
        <tr>
          <th>郵便番号</th>
          <th>住所</th>
          <th>宛名</th>
          <th colspan="2"></th>
        </tr>
      </thaed>
      <tbody>
        <% @addresses.each do |address| %>
        <tr>
          <td><%= address.postcode %></td>
          <td><%= address.address %></td>
          <td><%= address.name %></td>
          <td>
            <%= link_to "編集する", edit_address_path(address.id), class:"btn btn-danger" %>
          </td>
          <td>
            <%= link_to "削除する", address_path(address.id), method: :delete, class:"btn btn-warning text-light" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/about.html.erb
<div class="row mt-5 d-flex align-items-center justify-content-center">
    <div>
      <h1 class="d-flex align-items-center justify-content-center">About</h1><br>
      <p class="text-center">ながのCAKEは全国発送可能なケーキ屋さんです。</p>
      <p class="text-center">お子様からお年寄りの方までお召し上がりいただけるよう、</p>
      <p class="text-center">様々なバリエーションをご用意しております。</p>
      <p class="text-center">また、全国へ発送可能ですので、「いつ」でも「どこ」でもご注文いただけます。</p>
      <p class="text-center">ぜひご注文ください。</p>
    </div>
</div>
<div class="d-flex align-items-center justify-content-center">
  <%= image_tag('logo_b.png') %>
</div>

app/views/homes/top.html.erb
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-1">
      <%= render 'layouts/search_side_bar', genres: @genres %>
    </div>
    
    <div class="col-7">
      <div class="mb-0 d-flex align-items-center justify-content-center">
        <%= image_tag('logo_b.png') %>
      </div>
        <h3 class="m-4">新着商品</h3>


      <div class="items">
        <div class="row">
      <% @items.each do |item| %>
      
        <div class="col-3 p-2">
        <%= link_to public_item_path(item.id) do %>
          <%= image_tag item.get_product_image(200,200)%>
        <% end %><br>
        <%= item.name %><br>
      <% if item.is_active == true %>
        <%= item.price %>円
      <% end %>
        <% if item.is_active == true %>
          販売中
        <% else %>
          売切れ
        <% end %>
        </div>
      <% end %>
      
      </div>
    </div>
          
 
    </div>
    <div class="col-2">
    </div>
  </div>