config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
  end
  delete :cart_items, to: 'public/cart_items#destroy_all', as: 'cart_items'
  namespace :admin do
    resources :genres, only: [:new, :index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :order_items, only: [:update]

  end


  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
  end
  namespace :public do
    resources :items, only: [:index,:show] do
  collection do
        get 'search'
       end
    end
  end



  root to: 'homes#top'
  get "/homes/about" => "homes#about", as: 'about'

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    patch "/orders/:id/status" => "orders#status_update", as: "status"
    patch "/orders/:id/making_status" => "orders#making_status_update", as: "making_status"
  end


  namespace :public do
    post "/orders/confirm"=>"orders#confirm", as: 'confirm'
    get "/orders/thankyou"=>"orders#thankyou", as: 'thankyou'
    resources :orders, only: [:new, :index, :show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :public do
    resources :customers
  end

  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'public/customers#unsubscribe', as: 'customer_unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'public/customers#withdrawal', as: 'customers_withdrawal'

  namespace :admin do
    resources :customers
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true




  def  address_display
    '〒'  +  postcode  +  ' '  +  address  +  ' '  +  name
  
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    validates :quantity, presence: true
    def subtotal
        item.add_tax_price * quantity
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items, dependent: :destroy

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_item, dependent: :destroy
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    with_options presence: true do
      validates :name, uniqueness: true
      validates :body
      validates :genre_id
      validates :price
    end
    validates :is_active, inclusion:{in: [true, false]}
    has_one_attached :product_image
    
    def get_product_image(width, height)
      unless product_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpeg')
        product_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      product_image.variant(resize_to_limit: [width, height]).processed
    end
    def add_tax_price
        (self.price * 1.10).round
    end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { wait: 0 ,confirm: 1 ,product: 2 ,ready: 3 ,sent: 4 }
 
 def subtotal
  product.with_tax_price * quantity
 end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # 注文ステータス（0=着手不可 / 1=製作待ち / 2=製作中 / 3=製作完了）
  enum status: {impossible:0, wait:1, midst:2, completion:3}

  belongs_to :order
  belongs_to :item
  
  def subtotal
    item.add_tax_price * quantity
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController


def index
    @addresses = Address.all
    @address = Address.new
end

def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path
    else
      render :index
    end
end

def edit
    @address = Address.find(params[:id])
end

def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render :edit
    end
end

def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
end

private
def address_params
    params.require(:address).permit(:postcode, :address, :name)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @quantity = Item.count
    @genres = Genre.all
  end

  def about
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if abj.errors.any? %>
  <%= abj.errors.count %>件のエラーが発生しました
  <ul>
  <% abj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_search_side_bar.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="active text-center">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.genrename, search_public_items_path(genre_name: genre.genrename), :style=>"color:black" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="shadow-lg bg-danger">
      <nav class="navbar">
      <div class="container">
        <a href="/"><%= image_tag('logo_s.png') %></a>
        <ul class="nav nav-tabs">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to public_customer_path(current_customer), class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-user"></i> My page </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_items_path, class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-birthday-cake"></i> 商品一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_cart_items_path, class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-shopping-cart"></i> カート </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link text-white" do %>
                <span><i class="fas fa-sign-out-alt"></i> ログアウト </span>
              <% end %>
            </li>
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-light" type="submit">Search</button>
            </form>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_items_path, class:"nav-link text-white" do %>
                <span><i class="fas fa-birthday-cake"></i> 商品一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path, class:"nav-link text-white" do %>
                <span><i class="fas fa-users"></i> 会員一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_orders_path, class:"nav-link text-white" do %>
                 <span><i class="fas fa-users"></i> 注文履歴一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class:"nav-link text-white" do %>
                <span><i class="fas fa-tablet-alt"></i> ジャンル一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link text-white" %>
            </li>
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-light" type="submit">Search</button>
            </form>
          <% else %>
            <li class="nav-item">
              <%= link_to about_path, class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-address-card"></i> About </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_items_path, class:"nav-link text-white" do %>
                <span><i class="fas fa-birthday-cake"></i> 商品一覧 </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-user-plus"></i> Sign Up </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path, class:"nav-link mx-2 text-white" do %>
                <span><i class="fas fa-sign-in-alt"></i> Log in </span>
              <% end %>
            </li>
           <form class="form-inline">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-light" type="submit">Search</button>
            </form>
          <% end %>
        </ul>
        </nav>
    </header>
      <main class="xl-auto lg-auto md-auto">
          <%= yield %>
        </div>
      </main>
  </body>
</html>